# Generated by Django 5.2.4 on 2025-08-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VisitorLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("purpose", models.CharField(max_length=100)),
                ("entry_time", models.DateTimeField(auto_now_add=True)),
                ("exit_time", models.DateTimeField(blank=True, null=True)),
                ("contact", models.CharField(blank=True, max_length=20)),
                ("blacklist", models.BooleanField(default=False)),
            ],
        ),
    ]
