# Generated by Django 5.2.4 on 2025-08-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AMCContract",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("vendor", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("contact", models.CharField(max_length=100)),
                ("notes", models.TextField(blank=True)),
            ],
        ),
    ]
